# Generated by Django 5.2.4 on 2025-08-25 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(max_length=7, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hexadecimal color code (e.g., #RRGGBB).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
    ]
