# Generated by Django 5.2.4 on 2025-08-26 17:24

import inventory.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_color_hex_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(max_length=7, null=True, unique=True, validators=[inventory.validation.validate_hex_color]),
        ),
    ]
